### PR TITLE
Create lint_python.yml

### PR DESCRIPTION
**Pull request by austinsonger**
This change is [Reviewable](https://reviewable.io/reviews/mistio/mist-ce/1013)

### CODE REVIEW

**Review by asssaddd — COMMENTED** [review]
.

**Review by asssaddd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mistio/mist-ce/1013)* status: all files reviewed, 1 unresolved discussion (waiting on @austinsonger)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/mistio/mist-ce/1013#-N5LcloZA_gmysMa8oBv):*

**Review by asssaddd — COMMENTED** [review]
.

**Comment by d-mo** [comment]
Thank you for the contribution. However, we're using Gitlab CI instead of Github actions.

**Pull request closed without merging**
